# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qGZYRYbqX9OUkTrS1XvKmq-fVy-xokYS
"""

import pandas as pd

file_path = 'BAJFINANCE.csv'
stock_data = pd.read_csv(file_path)

stock_data.head()

import pandas as pd
import matplotlib.pyplot as plt

file_path = 'BAJFINANCE.csv'
stock_data = pd.read_csv(file_path)

stock_data['Date'] = pd.to_datetime(stock_data['Date'], errors='coerce')
stock_data = stock_data.dropna(subset=['Date'])

if stock_data['Close'].isnull().any():
    stock_data = stock_data.dropna(subset=['Close'])
plt.figure(figsize=(12, 6))
plt.plot(stock_data['Date'], stock_data['Close'], label='Closing Price')
plt.title('Closing Price Trend Over Time')
plt.xlabel('Date')
plt.ylabel('Closing Price')
plt.legend()
plt.show()